/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Scanner */

#ifndef _Included_Scanner
#define _Included_Scanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Scanner
 * Method:    OpenSCA
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cilico_Scan_Scanner_OpenSCA
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Scanner
 * Method:    CloseSCA
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Cilico_Scan_Scanner_CloseSCA
  (JNIEnv *, jclass, jint);

/*
 * Class:     Scanner
 * Method:    ScanSCA
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Cilico_Scan_Scanner_ScanSCA
  (JNIEnv *, jclass, jint);

/*
 * Class:     Scanner
 * Method:    ReadDataSCA
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_Cilico_Scan_ReadDataSCA
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
