drop table if exists 'token';
create table 'token' ('token_type' text not null, 'access_token' text not null, 'expires_in' integer not null, 'userName' text not null primary key, '.issued' text not null, '.expires' text not null);
drop table if exists 'equipment';
create table 'equipment' ('uuid' text not null primary key, 'title' text not null, 'equipment_type_uuid' text not null, 'critical_type_uuid' text not null, 'start_date' integer not null default 0, 'location' text not null, 'tag_id' text not null unique);
drop table if exists 'measure_value';
create table 'measure_value' ('uuid' text not null primary key, 'equipment_operation_uuid' text not null, 'operation_pattern_step_result' text not null, 'date' integer not null, 'value' text not null);
drop table if exists 'task';
create table 'task' ('uuid' text not null primary key, 'users_uuid' text not null, 'create_date' integer not null, 'modify_date' integer not null, 'close_date' integer not null default 0, 'task_status_uuid' text not null, 'attempt_send_date' integer not null default 0, 'attempt_count' integer not null default 0, 'successefull_send' integer not null default 0);
drop table if exists 'equipment_operation_result';
create table 'equipment_operation_result' ('uuid' text not null primary key, 'equipment_operation_uuid' text not null, 'start_date' integer not null, 'end_date' integer not null default 0, 'operation_result_uuid' text not null default '00000000-0000-0000-0000-000000000000');
