drop table if exists 'register';
drop table if exists 'measure_value';
create table 'measure_type' ('uuid' text not null primary key, title text not null);
drop table if exists 'operation_pattern_step_result';
create table 'operation_pattern_step_result' ('uuid' text not null primary key, 'operation_pattern_step_uuid' text not null, 'next_operation_pattern_step_uuid' text not null, 'title' text not null, 'measure_type_uuid' text default null);
drop table if exists 'measure_value';
create table 'measure_value' ('uuid' text not null primary key, 'equipment_operation_result' text not null, 'measure_value_type' text not null, 'date' text not null, 'value' text not null);
drop table if exists 'equipment_operation_result';
create table 'equipment_operation_result' ('uuid' text not null primary key, 'equipment_operation_uuid' text not null, 'start_date' text not null, 'end_date' text not null, 'operation_result_uuid' text not null default '');
drop table if exists 'var';
drop table if exists 'data';
drop table if exists 'events';
